import tkinter as tk
window=tk.Tk()
window.title("Simple Form")
window.geometry("400x200")
name=tk.Label(window,text="Name")
name.grid(row=0,column=0,padx=10,pady=10)
entry_name=tk.Entry(window)
entry_name.grid(row=0,column=1,padx=10,pady=10)
email=tk.Label(window,text="Email")
email.grid(row=1,column=0,padx=10,pady=10)
entry_email=tk.Entry(window)
entry_email.grid(row=1,column=1,padx=10,pady=10)
submit=tk.Button(window,text="Submit")
submit.grid(row=2,column=0,columnspan=2,pady=10)
window.mainloop()
